# Generated by Django 4.1.6 on 2023-02-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.CharField(blank=True, choices=[('Yes', 'Published'), ('No', 'Draft')], max_length=255),
        ),
    ]
