# Generated by Django 4.1.6 on 2023-02-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_blog_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
