# Generated by Django 4.1.6 on 2023-02-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_blog_blog_content_alter_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='metadata',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
