# Generated by Django 4.1.6 on 2023-02-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_blog_keywords_blog_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='contributor',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
