# Generated by Django 4.1.6 on 2023-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_blog_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contributor',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
