# Generated by Django 4.1.6 on 2023-02-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_blog_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rmv_contributor',
            field=models.BooleanField(default=False),
        ),
    ]
